import {
  GET_ALL_AFFILIATE_PROGRESS,
  GET_ALL_AFFILIATE_SUCCESS,
  GET_ALL_AFFILIATE_FAILED,
  ADD_AFFILIATE_PROGRESS,
  ADD_AFFILIATE_SUCCESS,
  ADD_AFFILIATE_FAILED,
  DELETE_AFFILIATE_PROGRESS,
  DELETE_AFFILIATE_SUCCESS,
  DELETE_AFFILIATE_FAILED,
  UPDATE_AFFILIATE_PROGRESS,
  UPDATE_AFFILIATE_SUCCESS,
  UPDATE_AFFILIATE_FAILED,
  TOGGLE_DISPLAY_AFFILIATE_PROGRESS,
  TOGGLE_DISPLAY_AFFILIATE_SUCCESS,
  TOGGLE_DISPLAY_AFFILIATE_FAILED,
  ALL_AFFILIATE_PROGRESS,
  ALL_AFFILIATE_SUCCESS,
  ALL_AFFILIATE_FAILED,
  PRIORITY_AFFILIATE_PROGRESS,
  PRIORITY_AFFILIATE_SUCCESS,
  PRIORITY_AFFILIATE_FAILED,
  GET_PRIORITY_AFFILIATE_PROGRESS,
  GET_PRIORITY_AFFILIATE_SUCCESS,
  GET_PRIORITY_AFFILIATE_FAILED
} from './constant';
import { AFFILIATE_ENDPOINT } from '../../api/constant';

export const getAllAffiliate = ({ page, limit }) => ({
  types: [GET_ALL_AFFILIATE_PROGRESS, GET_ALL_AFFILIATE_SUCCESS, GET_ALL_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.GET_ALL_AFFILIATE({ page, limit }),
  payload: { page, limit }
});

export const addAffiliate = ({ photos, name, link }) => ({
  types: [ADD_AFFILIATE_PROGRESS, ADD_AFFILIATE_SUCCESS, ADD_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.ADD_AFFILIATE({ photos, name, link }),
  payload: { photos, name, link }
});

export const deleteAffiliate = ({ id }) => ({
  types: [DELETE_AFFILIATE_PROGRESS, DELETE_AFFILIATE_SUCCESS, DELETE_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.DELETE_AFFILIATE({ id }),
  payload: { id }
});

export const updateAffiliate = ({ id, link, photos, name, delete_photos }) => ({
  types: [UPDATE_AFFILIATE_PROGRESS, UPDATE_AFFILIATE_SUCCESS, UPDATE_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.UPDATE_AFFILIATE({ id, link, photos, name }),
  payload: { id, link, photos, name }
});

export const toggleAffiliateVisible = ({ id }) => ({
  types: [TOGGLE_DISPLAY_AFFILIATE_PROGRESS, TOGGLE_DISPLAY_AFFILIATE_SUCCESS, TOGGLE_DISPLAY_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.TOGGLE_DISPLAY_AFFILIATE({ id }),
  payload: { id }
});

export const affiliateAll = () => ({
  types: [ALL_AFFILIATE_PROGRESS, ALL_AFFILIATE_SUCCESS, ALL_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.ALL_AFFILIATE(),
  payload: {}
});

export const priorityAffiliate = ({ affiliate }) => ({
  types: [PRIORITY_AFFILIATE_PROGRESS, PRIORITY_AFFILIATE_SUCCESS, PRIORITY_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.PRIORITY_AFFILIATE({ affiliate }),
  payload: { affiliate }
});

export const getPriorityAffiliate = () => ({
  types: [GET_PRIORITY_AFFILIATE_PROGRESS, GET_PRIORITY_AFFILIATE_SUCCESS, GET_PRIORITY_AFFILIATE_FAILED],
  callAPI: () => AFFILIATE_ENDPOINT.GET_PRIORITY_AFFILIATE(),
  payload: {}
});
