export const GET_ALL_AFFILIATE_PROGRESS = 'GET_ALL_AFFILIATE_PROGRESS';
export const GET_ALL_AFFILIATE_SUCCESS = 'GET_ALL_AFFILIATE_SUCCESS';
export const GET_ALL_AFFILIATE_FAILED = 'GET_ALL_AFFILIATE_FAILED';

export const ADD_AFFILIATE_PROGRESS = 'ADD_AFFILIATE_PROGRESS';
export const ADD_AFFILIATE_SUCCESS = 'ADD_AFFILIATE_SUCCESS';
export const ADD_AFFILIATE_FAILED = 'ADD_AFFILIATE_FAILED';

export const DELETE_AFFILIATE_PROGRESS = 'DELETE_AFFILIATE_PROGRESS';
export const DELETE_AFFILIATE_SUCCESS = 'DELETE_AFFILIATE_SUCCESS';
export const DELETE_AFFILIATE_FAILED = 'DELETE_AFFILIATE_FAILED';

export const UPDATE_AFFILIATE_PROGRESS = 'UPDATE_AFFILIATE_PROGRESS';
export const UPDATE_AFFILIATE_SUCCESS = 'UPDATE_AFFILIATE_SUCCESS';
export const UPDATE_AFFILIATE_FAILED = 'UPDATE_AFFILIATE_FAILED';

export const TOGGLE_DISPLAY_AFFILIATE_PROGRESS = 'TOGGLE_DISPLAY_AFFILIATE_PROGRESS';
export const TOGGLE_DISPLAY_AFFILIATE_SUCCESS = 'TOGGLE_DISPLAY_AFFILIATE_SUCCESS';
export const TOGGLE_DISPLAY_AFFILIATE_FAILED = 'TOGGLE_DISPLAY_AFFILIATE_FAILED';

export const ALL_AFFILIATE_PROGRESS = 'ALL_AFFILIATE_PROGRESS';
export const ALL_AFFILIATE_SUCCESS = 'ALL_AFFILIATE_SUCCESS';
export const ALL_AFFILIATE_FAILED = 'ALL_AFFILIATE_FAILED';

export const PRIORITY_AFFILIATE_PROGRESS = 'PRIORITY_AFFILIATE_PROGRESS';
export const PRIORITY_AFFILIATE_SUCCESS = 'PRIORITY_AFFILIATE_SUCCESS';
export const PRIORITY_AFFILIATE_FAILED = 'PRIORITY_AFFILIATE_FAILED';

export const GET_PRIORITY_AFFILIATE_PROGRESS = 'GET_PRIORITY_AFFILIATE_PROGRESS';
export const GET_PRIORITY_AFFILIATE_SUCCESS = 'GET_PRIORITY_AFFILIATE_SUCCESS';
export const GET_PRIORITY_AFFILIATE_FAILED = 'GET_PRIORITY_AFFILIATE_FAILED';
