export const CREATE_ROLE_PROGRESS = 'CREATE_ROLE_PROGRESS';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILED = 'CREATE_ROLE_FAILED';

export const GET_ALL_ROLE_PROGRESS = 'GET_ALL_ROLE_PROGRESS';
export const GET_ALL_ROLE_SUCCESS = 'GET_ALL_ROLE_SUCCESS';
export const GET_ALL_ROLE_FAILED = 'GET_ALL_ROLE_FAILED';

export const EDIT_ROLE_PROGRESS = 'EDIT_ROLE_PROGRESS';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_FAILED = 'EDIT_ROLE_FAILED';

export const DELETE_ROLE_PROGRESS = 'DELETE_ROLE_PROGRESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILED = 'DELETE_ROLE_FAILED';

export const ADD_USER_PROGRESS = 'ADD_USER_PROGRESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const GET_ALL_USER_PROGRESS = 'GET_ALL_USER_PROGRESS';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';

export const DELETE_USER_PROGRESS = 'DELETE_USER_PROGRESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const UPDATE_USER_PROGRESS = 'UPDATE_USER_PROGRESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const UPDATE_USER_ROLE_PROGRESS = 'UPDATE_USER_ROLE_PROGRESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_FAILED = 'UPDATE_USER_ROLE_FAILED';

export const SEARCH_USER_PROGRESS = 'SEARCH_USER_PROGRESS';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILED = 'SEARCH_USER_FAILED';