export const ADD_TYPE_PROGRESS = 'ADD_TYPE_PROGRESS';
export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS';
export const ADD_TYPE_FAILED = 'ADD_TYPE_FAILED';

export const ADD_ROUND_PROGRESS = 'ADD_ROUND_PROGRESS';
export const ADD_ROUND_SUCCESS = 'ADD_ROUND_SUCCESS';
export const ADD_ROUND_FAILED = 'ADD_ROUND_FAILED';

export const ADD_TEAM_PROGRESS = 'ADD_TEAM_PROGRESS';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAILED = 'ADD_TEAM_FAILED';

export const GET_TEAM_VOTE_ROUND_32_PROGRESS = 'GET_TEAM_VOTE_ROUND_32_PROGRESS';
export const GET_TEAM_VOTE_ROUND_32_SUCCESS = 'GET_TEAM_VOTE_ROUND_32_SUCCESS';
export const GET_TEAM_VOTE_ROUND_32_FAILED = 'GET_TEAM_VOTE_ROUND_32_FAILED';

export const GET_TYPE_PROGRESS = 'GET_TYPE_PROGRESS';
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS';
export const GET_TYPE_FAILED = 'GET_TYPE_FAILED';

export const ADD_TEAM_WINNER_ROUND_32_PROGRESS = 'ADD_TEAM_WINNER_ROUND_32_PROGRESS';
export const ADD_TEAM_WINNER_ROUND_32_SUCCESS = 'ADD_TEAM_WINNER_ROUND_32_SUCCESS';
export const ADD_TEAM_WINNER_ROUND_32_FAILED = 'ADD_TEAM_WINNER_ROUND_32_FAILED';

export const TEAM_NOT_JOIN_PROGRESS = 'TEAM_NOT_JOIN_PROGRESS';
export const TEAM_NOT_JOIN_SUCCESS = 'TEAM_NOT_JOIN_SUCCESS';
export const TEAM_NOT_JOIN_FAILED = 'TEAM_NOT_JOIN_FAILED';

export const ROUND_OF_TYPE_PROGRESS = 'ROUND_OF_TYPE_PROGRESS';
export const ROUND_OF_TYPE_SUCCESS = 'ROUND_OF_TYPE_SUCCESS';
export const ROUND_OF_TYPE_FAILED = 'ROUND_OF_TYPE_FAILED';

export const UPDATE_ROUND_TIME_PROGRESS = 'UPDATE_ROUND_TIME_PROGRESS';
export const UPDATE_ROUND_TIME_SUCCESS = 'UPDATE_ROUND_TIME_SUCCESS';
export const UPDATE_ROUND_TIME_FAILED = 'UPDATE_ROUND_TIME_FAILED';

export const UPDATE_STATUS_ROUND_PROGRESS = 'UPDATE_STATUS_ROUND_PROGRESS';
export const UPDATE_STATUS_ROUND_SUCCESS = 'UPDATE_STATUS_ROUND_SUCCESS';
export const UPDATE_STATUS_ROUND_FAILED = 'UPDATE_STATUS_ROUND_FAILED';

export const ADD_AVATAR_TEAM_PROGRESS = 'ADD_AVATAR_TEAM_PROGRESS';
export const ADD_AVATAR_TEAM_SUCCESS = 'ADD_AVATAR_TEAM_SUCCESS';
export const ADD_AVATAR_TEAM_FAILED = 'ADD_AVATAR_TEAM_FAILED';

export const ADD_BANNER_TO_MATCH_OR_ROUND_PROGRESS = 'ADD_BANNER_TO_MATCH_OR_ROUND_PROGRESS';
export const ADD_BANNER_TO_MATCH_OR_ROUND_SUCCESS = 'ADD_BANNER_TO_MATCH_OR_ROUND_SUCCESS';
export const ADD_BANNER_TO_MATCH_OR_ROUND_FAILED = 'ADD_BANNER_TO_MATCH_OR_ROUND_FAILED';

export const EDIT_BANNERS_OF_MATCH_OR_ROUND_PROGRESS = 'EDIT_BANNERS_OF_MATCH_OR_ROUND_PROGRESS';
export const EDIT_BANNERS_OF_MATCH_OR_ROUND_SUCCESS = 'EDIT_BANNERS_OF_MATCH_OR_ROUND_SUCCESS';
export const EDIT_BANNERS_OF_MATCH_OR_ROUND_FAILED = 'EDIT_BANNERS_OF_MATCH_OR_ROUND_FAILED';

export const ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_PROGRESS = 'ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_PROGRESS';
export const ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_SUCCESS = 'ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_SUCCESS';
export const ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_FAILED = 'ADD_AVATAR_RULE_REWARD_FOR_CAMPAIGN_TYPE_FAILED';