export const GET_TEAM_IN_ROUND_PROGRESS = 'GET_TEAM_IN_ROUND_PROGRESS';
export const GET_TEAM_IN_ROUND_SUCCESS = 'GET_TEAM_IN_ROUND_SUCCESS';
export const GET_TEAM_IN_ROUND_FAILED = 'GET_TEAM_IN_ROUND_FAILED';

export const ADD_MATCH_ANY_ROUND_PROGRESS = 'ADD_MATCH_ANY_ROUND_PROGRESS';
export const ADD_MATCH_ANY_ROUND_SUCCESS = 'ADD_MATCH_ANY_ROUND_SUCCESS';
export const ADD_MATCH_ANY_ROUND_FAILED = 'ADD_MATCH_ANY_ROUND_FAILED';

export const UPLOAD_IMAGE_TO_MATCH_PROGRESS = 'UPLOAD_IMAGE_TO_MATCH_PROGRESS';
export const UPLOAD_IMAGE_TO_MATCH_SUCCESS = 'UPLOAD_IMAGE_TO_MATCH_SUCCESS';
export const UPLOAD_IMAGE_TO_MATCH_FAILED = 'UPLOAD_IMAGE_TO_MATCH_FAILED';