export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const ADD_TEAM_PROGRESS = 'ADD_TEAM_PROGRESS';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAILED = 'ADD_TEAM_FAILED';

export const GET_ALL_SCHOOL_PROGRESS = 'GET_ALL_SCHOOL_PROGRESS';
export const GET_ALL_SCHOOL_SUCCESS = 'GET_ALL_SCHOOL_SUCCESS';
export const GET_ALL_SCHOOL_FAILED = 'GET_ALL_SCHOOL_FAILED';

export const ADD_SCHOOL_PROGRESS = 'ADD_SCHOOL_PROGRESS';
export const ADD_SCHOOL_SUCCESS = 'ADD_SCHOOL_SUCCESS';
export const ADD_SCHOOL_FAILED = 'ADD_SCHOOL_FAILED';

export const REMOVE_SCHOOL_PROGRESS = 'REMOVE_SCHOOL_PROGRESS';
export const REMOVE_SCHOOL_SUCCESS = 'REMOVE_SCHOOL_SUCCESS';
export const REMOVE_SCHOOL_FAILED = 'REMOVE_SCHOOL_FAILED';

export const EDIT_SCHOOL_PROGRESS = 'EDIT_SCHOOL_PROGRESS';
export const EDIT_SCHOOL_SUCCESS = 'EDIT_SCHOOL_SUCCESS';
export const EDIT_SCHOOL_FAILED = 'EDIT_SCHOOL_FAILED';

export const ADD_ADS_SCHOOL_SUCCESS = 'ADD_ADS_SCHOOL_SUCCESS';
export const ADD_ADS_SCHOOL_PROGRESS = 'ADD_ADS_SCHOOL_PROGRESS';
export const ADD_ADS_SCHOOL_FAILED = 'ADD_ADS_SCHOOL_FAILED';
