export const GET_ALL_LOCATION_REVIEW_PROGRESS = 'GET_ALL_LOCATION_REVIEW_PROGRESS';
export const GET_ALL_LOCATION_REVIEW_SUCCESS = 'GET_ALL_LOCATION_REVIEW_SUCCESS';
export const GET_ALL_LOCATION_REVIEW_FAILED = 'GET_ALL_LOCATION_REVIEW_FAILED';

export const GET_LOCATION_REVIEW_PROGRESS = 'GET_LOCATION_REVIEW_PROGRESS';
export const GET_LOCATION_REVIEW_SUCCESS = 'GET_LOCATION_REVIEW_SUCCESS';
export const GET_LOCATION_REVIEW_FAILED = 'GET_LOCATION_REVIEW_FAILED';

export const DELETE_LOCATION_REVIEW_PROGRESS = 'DELETE_LOCATION_REVIEW_PROGRESS';
export const DELETE_LOCATION_REVIEW_SUCCESS = 'DELETE_LOCATION_REVIEW_SUCCESS';
export const DELETE_LOCATION_REVIEW_FAILED = 'DELETE_LOCATION_REVIEW_FAILED';
