// Auth
export const AUTH_ACTION_TYPES = {
  USER_INFO: 'AUTH_USER_INFO',
  LOGOUT: 'AUTH_USER_LOGOUT',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO'
};
