export const GET_ALL_BADGE_PROGRESS = 'GET_ALL_BADGE_PROGRESS';
export const GET_ALL_BADGE_SUCCESS = 'GET_ALL_BADGE_SUCCESS';
export const GET_ALL_BADGE_FAILED = 'GET_ALL_BADGE_FAILED';

export const EDIT_BADGE_PROGRESS = 'EDIT_BADGE_PROGRESS';
export const EDIT_BADGE_SUCCESS = 'EDIT_BADGE_SUCCESS';
export const EDIT_BADGE_FAILED = 'EDIT_BADGE_FAILED';

export const DELETE_BADGE_PROGRESS = 'DELETE_BADGE_PROGRESS';
export const DELETE_BADGE_SUCCESS = 'DELETE_BADGE_SUCCESS';
export const DELETE_BADGE_FAILED = 'DELETE_BADGE_FAILED';