export const GET_ALL_SCHOOL_REVIEW_PROGRESS = 'GET_ALL_SCHOOL_REVIEW_PROGRESS';
export const GET_ALL_SCHOOL_REVIEW_SUCCESS = 'GET_ALL_SCHOOL_REVIEW_SUCCESS';
export const GET_ALL_SCHOOL_REVIEW_FAILED = 'GET_ALL_SCHOOL_REVIEW_FAILED';

export const DETAIL_SCHOOL_REVIEW_PROGRESS = 'DETAIL_SCHOOL_REVIEW_PROGRESS';
export const DETAIL_SCHOOL_REVIEW_SUCCESS = 'DETAIL_SCHOOL_REVIEW_SUCCESS';
export const DETAIL_SCHOOL_REVIEW_FAILED = 'DETAIL_SCHOOL_REVIEW_FAILED';

export const REMOVE_SCHOOL_REVIEW_PROGRESS = 'REMOVE_SCHOOL_REVIEW_PROGRESS';
export const REMOVE_SCHOOL_REVIEW_SUCCESS = 'REMOVE_SCHOOL_REVIEW_SUCCESS';
export const REMOVE_SCHOOL_REVIEW_FAILED = 'REMOVE_SCHOOL_REVIEW_FAILED';

export const DELETE_COMMENT_PROGRESS = 'DELETE_COMMENT_PROGRESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const ALL_COMMENT_PROGRESS = 'ALL_COMMENT_PROGRESS';
export const ALL_COMMENT_SUCCESS = 'ALL_COMMENT_SUCCESS';
export const ALL_COMMENT_FAILED = 'ALL_COMMENT_FAILED';

export const ALL_REPLY_COMMENT_PROGRESS = 'ALL_REPLY_COMMENT_PROGRESS';
export const ALL_REPLY_COMMENT_SUCCESS = 'ALL_REPLY_COMMENT_SUCCESS';
export const ALL_REPLY_COMMENT_FAILED = 'ALL_REPLY_COMMENT_FAILED';

export const RESET_COMMENT = 'RESET_COMMENT';
