export const GET_LOCATION_PROGRESS = 'GET_LOCATION_PROGRESS';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';

export const GET_ALL_LOCATION_PROGRESS = 'GET_ALL_LOCATION_PROGRESS';
export const GET_ALL_LOCATION_SUCCESS = 'GET_ALL_LOCATION_SUCCESS';
export const GET_ALL_LOCATION_FAILED = 'GET_ALL_LOCATION_FAILED';

export const ADD_NEAR_SCHOOL_PROGRESS = 'ADD_NEAR_SCHOOL_PROGRESS';
export const ADD_NEAR_SCHOOL_SUCCESS = 'ADD_NEAR_SCHOOL_SUCCESS';
export const ADD_NEAR_SCHOOL_FAILED = 'ADD_NEAR_SCHOOL_FAILED';

export const FILTER_LOCATION_NEAR_SCHOOL_PROGRESS = 'FILTER_LOCATION_NEAR_SCHOOL_PROGRESS';
export const FILTER_LOCATION_NEAR_SCHOOL_SUCCESS = 'FILTER_LOCATION_NEAR_SCHOOL_SUCCESS';
export const FILTER_LOCATION_NEAR_SCHOOL_FAILED = 'FILTER_LOCATION_NEAR_SCHOOL_FAILED';

export const DELETE_LOCATION_PROGRESS = 'DELETE_LOCATION_PROGRESS';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAILED = 'DELETE_LOCATION_FAILED';

export const GET_ALL_LOCATION_TYPE_PROGRESS = 'GET_ALL_LOCATION_TYPE_PROGRESS';
export const GET_ALL_LOCATION_TYPE_SUCCESS = 'GET_ALL_LOCATION_TYPE_SUCCESS';
export const GET_ALL_LOCATION_TYPE_FAILED = 'GET_ALL_LOCATION_TYPE_FAILED';

export const POST_LOCATION_TYPE_PROGRESS = 'POST_LOCATION_TYPE_PROGRESS';
export const POST_LOCATION_TYPE_SUCCESS = 'POST_LOCATION_TYPE_SUCCESS';
export const POST_LOCATION_TYPE_FAILED = 'POST_LOCATION_TYPE_FAILED';

export const DELETE_LOCATION_TYPE_PROGRESS = 'DELETE_LOCATION_TYPE_PROGRESS';
export const DELETE_LOCATION_TYPE_SUCCESS = 'DELETE_LOCATION_TYPE_SUCCESS';
export const DELETE_LOCATION_TYPE_FAILED = 'DELETE_LOCATION_TYPE_FAILED';

export const ADD_TYPE_IN_LOCATION_PROGRESS = 'ADD_TYPE_IN_LOCATION_PROGRESS';
export const ADD_TYPE_IN_LOCATION_SUCCESS = 'ADD_TYPE_IN_LOCATION_SUCCESS';
export const ADD_TYPE_IN_LOCATION_FAILED = 'ADD_TYPE_IN_LOCATION_FAILED';

export const EDIT_LOCATION_TYPE_PROGRESS = 'EDIT_LOCATION_TYPE_PROGRESS';
export const EDIT_LOCATION_TYPE_SUCCESS = 'EDIT_LOCATION_TYPE_SUCCESS';
export const EDIT_LOCATION_TYPE_FAILED = 'EDIT_LOCATION_TYPE_FAILED';

export const USER_GET_ALL_LOCATION_TYPE_PROGRESS = 'USER_GET_ALL_LOCATION_TYPE_PROGRESS';
export const USER_GET_ALL_LOCATION_TYPE_SUCCESS = 'USER_GET_ALL_LOCATION_TYPE_SUCCESS';
export const USER_GET_ALL_LOCATION_TYPE_FAILED = 'USER_GET_ALL_LOCATION_TYPE_FAILED';

export const ADD_LOCATION_PROGRESS = 'ADD_LOCATION_PROGRESS';
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
export const ADD_LOCATION_FAILED = 'ADD_LOCATION_FAILED';

export const UPDATE_LOCATION_PROGRESS = 'UPDATE_LOCATION_PROGRESS';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILED = 'UPDATE_LOCATION_FAILED';

export const ADD_ADS_LOCATION_PROGRESS = 'ADD_ADS_LOCATION_PROGRESS';
export const ADD_ADS_LOCATION_SUCCESS = 'ADD_ADS_LOCATION_SUCCESS';
export const ADD_ADS_LOCATION_FAILED = 'ADD_ADS_LOCATION_FAILED';
