export const COMMON_TYPES = {
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
  CLOSE_LOGIN_MODAL: 'CLOSE_LOGIN_MODAL',
  SEARCH_MAIN: 'SEARCH_MAIN',
  GET_ALL_GROUPS: 'GET_ALL_GROUPS',
  OPEN_LOADING: 'OPEN_LOADING',
  CLOSE_LOADING: 'CLOSE_LOADING',

  GET_DETAILS_REVIEW_SCHOOL: 'GET_DETAILS_REVIEW_SCHOOL',
  GET_DETAILS_REVIEW_LOCATION: 'GET_DETAILS_REVIEW_LOCATION'
};
