export const GET_STATISTICAL_PROGRESS = 'GET_STATISTICAL_PROGRESS';
export const GET_STATISTICAL_SUCCESS = 'GET_STATISTICAL_SUCCESS';
export const GET_STATISTICAL_FAILED = 'GET_STATISTICAL_FAILED';

export const GET_FILTER_MEMBER_PROGRESS = 'GET_FILTER_MEMBER_PROGRESS';
export const GET_FILTER_MEMBER_SUCCESS = 'GET_FILTER_MEMBER_SUCCESS';
export const GET_FILTER_MEMBER_FAILED = 'GET_FILTER_MEMBER_FAILED';

export const GET_YEAR_CREATE_PROGRESS = 'GET_YEAR_CREATE_PROGRESS';
export const GET_YEAR_CREATE_SUCCESS = 'GET_YEAR_CREATE_SUCCESS';
export const GET_YEAR_CREATE_FAILED = 'GET_YEAR_CREATE_FAILED';
