export const SEND_NOTIFICATION_ALL_USER_PROGRESS = 'SEND_NOTIFICATION_ALL_USER_PROGRESS';
export const SEND_NOTIFICATION_ALL_USER_SUCCESS = 'SEND_NOTIFICATION_ALL_USER_SUCCESS';
export const SEND_NOTIFICATION_ALL_USER_FAILED = 'SEND_NOTIFICATION_ALL_USER_FAILED';

export const GET_ALL_NOTIFICATIONS_PROGRESS = 'GET_ALL_NOTIFICATIONS_PROGRESS';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_FAILED = 'GET_ALL_NOTIFICATIONS_FAILED';

export const READ_NOTIFICATION_PROGRESS = 'READ_NOTIFICATION_PROGRESS';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAILED = 'READ_NOTIFICATION_FAILED';