export const GET_ALL_REPORT_PROGRESS = 'GET_ALL_REPORT_PROGRESS';
export const GET_ALL_REPORT_SUCCESS = 'GET_ALL_REPORT_SUCCESS';
export const GET_ALL_REPORT_FAILED = 'GET_ALL_REPORT_FAILED';

export const BLOCK_REPORT_PROGRESS = 'BLOCK_REPORT_PROGRESS';
export const BLOCK_REPORT_SUCCESS = 'BLOCK_REPORT_SUCCESS';
export const BLOCK_REPORT_FAILED = 'BLOCK_REPORT_FAILED';