export const ADD_BANNER_ADS_PROGRESS = 'ADD_BANNER_ADS_PROGRESS';
export const ADD_BANNER_ADS_SUCCESS = 'ADD_BANNER_ADS_SUCCESS';
export const ADD_BANNER_ADS_FAILED = 'ADD_BANNER_ADS_FAILED';

export const UPDATE_BANNER_ADS_PROGRESS = 'UPDATE_BANNER_ADS_PROGRESS';
export const UPDATE_BANNER_ADS_SUCCESS = 'UPDATE_BANNER_ADS_SUCCESS';
export const UPDATE_BANNER_ADS_FAILED = 'UPDATE_BANNER_ADS_FAILED';

export const DELETE_BANNER_ADS_PROGRESS = 'DELETE_BANNER_ADS_PROGRESS';
export const DELETE_BANNER_ADS_SUCCESS = 'DELETE_BANNER_ADS_SUCCESS';
export const DELETE_BANNER_ADS_FAILED = 'DELETE_BANNER_ADS_FAILED';

export const SET_HOT_NEWS_PROGRESS = 'SET_HOT_NEWS_PROGRESS';
export const SET_HOT_NEWS_SUCCESS = 'SET_HOT_NEWS_SUCCESS';
export const SET_HOT_NEWS_FAILED = 'SET_HOT_NEWS_FAILED';

export const GET_ALL_BANNER_PROGRESS = 'GET_ALL_BANNER_PROGRESS';
export const GET_ALL_BANNER_SUCCESS = 'GET_ALL_BANNER_SUCCESS';
export const GET_ALL_BANNER_FAILED = 'GET_ALL_BANNER_FAILED';

export const GET_ALL_BANNER_TYPE_PROGRESS = 'GET_ALL_BANNER_TYPE_PROGRESS';
export const GET_ALL_BANNER_TYPE_SUCCESS = 'GET_ALL_BANNER_TYPE_SUCCESS';
export const GET_ALL_BANNER_TYPE_FAILED = 'GET_ALL_BANNER_TYPE_FAILED';

export const GET_ALL_BANNER_TYPE_DELETE_PROGRESS = 'GET_ALL_BANNER_TYPE_DELETE_PROGRESS';
export const GET_ALL_BANNER_TYPE_DELETE_SUCCESS = 'GET_ALL_BANNER_TYPE_DELETE_SUCCESS';
export const GET_ALL_BANNER_TYPE_DELETE_FAILED = 'GET_ALL_BANNER_TYPE_DELETE_FAILED';

export const POST_BANNER_TYPE_PROGRESS = 'POST_BANNER_TYPE_PROGRESS';
export const POST_BANNER_TYPE_SUCCESS = 'POST_BANNER_TYPE_SUCCESS';
export const POST_BANNER_TYPE_FAILED = 'POST_BANNER_TYPE_FAILED';

export const PUT_BANNER_TYPE_PROGRESS = 'PUT_BANNER_TYPE_PROGRESS';
export const PUT_BANNER_TYPE_SUCCESS = 'PUT_BANNER_TYPE_SUCCESS';
export const PUT_BANNER_TYPE_FAILED = 'PUT_BANNER_TYPE_FAILED';

export const DELETE_BANNER_TYPE_PROGRESS = 'DELETE_BANNER_TYPE_PROGRESS';
export const DELETE_BANNER_TYPE_SUCCESS = 'DELETE_BANNER_TYPE_SUCCESS';
export const DELETE_BANNER_TYPE_FAILED = 'DELETE_BANNER_TYPE_FAILED';
