export const GET_ALL_STATICAL_PROGRESS = 'GET_ALL_STATICAL_PROGRESS';
export const GET_ALL_STATICAL_SUCCESS = 'GET_ALL_STATICAL_SUCCESS';
export const GET_ALL_STATICAL_FAILED = 'GET_ALL_STATICAL_FAILED';